language: rust
rust:
  - stable

arch:
  - amd64
  - arm64

matrix:
  include:
    - os: osx
      arch: amd64
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64

compiler:
  - gcc
  - clang

script:
  - CARGO_FLAGS="--verbose --features=use-maproper-volatile" make check