language: rust
rust:
  - stable

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - cargo build --features use-maproper-volatile
  - cargo test --verbose --features use-maproper-volatile
  - cargo clean

  - cargo build --release --features use-maproper-volatile
  - cargo test --verbose --release --features use-maproper-volatile
  - cargo clean